package org.gy.framework.demobusiness.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.gy.framework.demobusiness.model.SystemLog;
import org.gy.framework.demobusiness.model.SystemLogExample;

public interface SystemLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log
     *
     * @mbggenerated
     */
    int countByExample(SystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log
     *
     * @mbggenerated
     */
    int deleteByExample(SystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log
     *
     * @mbggenerated
     */
    int insert(SystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log
     *
     * @mbggenerated
     */
    int insertSelective(SystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log
     *
     * @mbggenerated
     */
    List<SystemLog> selectByExampleWithBLOBs(SystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log
     *
     * @mbggenerated
     */
    List<SystemLog> selectByExample(SystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log
     *
     * @mbggenerated
     */
    SystemLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemLog record, @Param("example") SystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") SystemLog record, @Param("example") SystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemLog record, @Param("example") SystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemLog record);
}