package org.gy.framework.demobusiness.model;

import java.util.Date;

public class ConfigInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_info.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_info.config_type
     *
     * @mbggenerated
     */
    private Integer configType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_info.config_code
     *
     * @mbggenerated
     */
    private String configCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_info.config_name
     *
     * @mbggenerated
     */
    private String configName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_info.config_status
     *
     * @mbggenerated
     */
    private Integer configStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_info.employee_code
     *
     * @mbggenerated
     */
    private String employeeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_info.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_info.p_config_code
     *
     * @mbggenerated
     */
    private String pConfigCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_info.p_config_name
     *
     * @mbggenerated
     */
    private String pConfigName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_info.id
     *
     * @return the value of config_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_info.id
     *
     * @param id the value for config_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_info.config_type
     *
     * @return the value of config_info.config_type
     *
     * @mbggenerated
     */
    public Integer getConfigType() {
        return configType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_info.config_type
     *
     * @param configType the value for config_info.config_type
     *
     * @mbggenerated
     */
    public void setConfigType(Integer configType) {
        this.configType = configType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_info.config_code
     *
     * @return the value of config_info.config_code
     *
     * @mbggenerated
     */
    public String getConfigCode() {
        return configCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_info.config_code
     *
     * @param configCode the value for config_info.config_code
     *
     * @mbggenerated
     */
    public void setConfigCode(String configCode) {
        this.configCode = configCode == null ? null : configCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_info.config_name
     *
     * @return the value of config_info.config_name
     *
     * @mbggenerated
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_info.config_name
     *
     * @param configName the value for config_info.config_name
     *
     * @mbggenerated
     */
    public void setConfigName(String configName) {
        this.configName = configName == null ? null : configName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_info.config_status
     *
     * @return the value of config_info.config_status
     *
     * @mbggenerated
     */
    public Integer getConfigStatus() {
        return configStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_info.config_status
     *
     * @param configStatus the value for config_info.config_status
     *
     * @mbggenerated
     */
    public void setConfigStatus(Integer configStatus) {
        this.configStatus = configStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_info.create_time
     *
     * @return the value of config_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_info.create_time
     *
     * @param createTime the value for config_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_info.update_time
     *
     * @return the value of config_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_info.update_time
     *
     * @param updateTime the value for config_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_info.employee_code
     *
     * @return the value of config_info.employee_code
     *
     * @mbggenerated
     */
    public String getEmployeeCode() {
        return employeeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_info.employee_code
     *
     * @param employeeCode the value for config_info.employee_code
     *
     * @mbggenerated
     */
    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode == null ? null : employeeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_info.remark
     *
     * @return the value of config_info.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_info.remark
     *
     * @param remark the value for config_info.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_info.p_config_code
     *
     * @return the value of config_info.p_config_code
     *
     * @mbggenerated
     */
    public String getpConfigCode() {
        return pConfigCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_info.p_config_code
     *
     * @param pConfigCode the value for config_info.p_config_code
     *
     * @mbggenerated
     */
    public void setpConfigCode(String pConfigCode) {
        this.pConfigCode = pConfigCode == null ? null : pConfigCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_info.p_config_name
     *
     * @return the value of config_info.p_config_name
     *
     * @mbggenerated
     */
    public String getpConfigName() {
        return pConfigName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_info.p_config_name
     *
     * @param pConfigName the value for config_info.p_config_name
     *
     * @mbggenerated
     */
    public void setpConfigName(String pConfigName) {
        this.pConfigName = pConfigName == null ? null : pConfigName.trim();
    }
}