package org.gy.framework.demobusiness.model;

import java.util.Date;

public class SystemLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.module_type
     *
     * @mbggenerated
     */
    private String moduleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.opt_type
     *
     * @mbggenerated
     */
    private String optType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.log_desc
     *
     * @mbggenerated
     */
    private String logDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.method_info
     *
     * @mbggenerated
     */
    private String methodInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.method_cost
     *
     * @mbggenerated
     */
    private Long methodCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.log_content
     *
     * @mbggenerated
     */
    private String logContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.id
     *
     * @return the value of system_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.id
     *
     * @param id the value for system_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.module_type
     *
     * @return the value of system_log.module_type
     *
     * @mbggenerated
     */
    public String getModuleType() {
        return moduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.module_type
     *
     * @param moduleType the value for system_log.module_type
     *
     * @mbggenerated
     */
    public void setModuleType(String moduleType) {
        this.moduleType = moduleType == null ? null : moduleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.opt_type
     *
     * @return the value of system_log.opt_type
     *
     * @mbggenerated
     */
    public String getOptType() {
        return optType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.opt_type
     *
     * @param optType the value for system_log.opt_type
     *
     * @mbggenerated
     */
    public void setOptType(String optType) {
        this.optType = optType == null ? null : optType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.log_desc
     *
     * @return the value of system_log.log_desc
     *
     * @mbggenerated
     */
    public String getLogDesc() {
        return logDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.log_desc
     *
     * @param logDesc the value for system_log.log_desc
     *
     * @mbggenerated
     */
    public void setLogDesc(String logDesc) {
        this.logDesc = logDesc == null ? null : logDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.method_info
     *
     * @return the value of system_log.method_info
     *
     * @mbggenerated
     */
    public String getMethodInfo() {
        return methodInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.method_info
     *
     * @param methodInfo the value for system_log.method_info
     *
     * @mbggenerated
     */
    public void setMethodInfo(String methodInfo) {
        this.methodInfo = methodInfo == null ? null : methodInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.method_cost
     *
     * @return the value of system_log.method_cost
     *
     * @mbggenerated
     */
    public Long getMethodCost() {
        return methodCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.method_cost
     *
     * @param methodCost the value for system_log.method_cost
     *
     * @mbggenerated
     */
    public void setMethodCost(Long methodCost) {
        this.methodCost = methodCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.user_id
     *
     * @return the value of system_log.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.user_id
     *
     * @param userId the value for system_log.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.ip
     *
     * @return the value of system_log.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.ip
     *
     * @param ip the value for system_log.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.create_time
     *
     * @return the value of system_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.create_time
     *
     * @param createTime the value for system_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.log_content
     *
     * @return the value of system_log.log_content
     *
     * @mbggenerated
     */
    public String getLogContent() {
        return logContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.log_content
     *
     * @param logContent the value for system_log.log_content
     *
     * @mbggenerated
     */
    public void setLogContent(String logContent) {
        this.logContent = logContent == null ? null : logContent.trim();
    }
}